# Generated by Django 5.1.4 on 2024-12-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showtimes", "0005_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
