# Generated by Django 5.1.4 on 2024-12-23 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showtimes", "0007_alter_movie_options_movie_naver_link"),
        ("single_pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name="showtime",
            old_name="show_time",
            new_name="showtime",
        ),
        migrations.AddField(
            model_name="showtime",
            name="location",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="showtimes_at_location",
                to="single_pages.movielocation",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="showtime",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="showtimes",
                to="single_pages.movie",
            ),
        ),
        migrations.CreateModel(
            name="MovieLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "chain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="showtimes.moviechain",
                    ),
                ),
            ],
        ),
    ]
