# Generated by Django 5.1.4 on 2024-12-23 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showtimes", "0011_location_alter_showtime_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showtime",
            name="location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="showtimes.location",
            ),
        ),
    ]
