# Generated by Django 5.1.4 on 2024-12-23 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showtimes", "0012_alter_showtime_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showtime",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="showtimes.location",
            ),
        ),
    ]
