# Generated by Django 5.1.4 on 2024-12-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showtimes", "0014_remove_showtime_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="cookie_status",
            field=models.BooleanField(default=False),
        ),
    ]
