# Generated by Django 5.1.4 on 2024-12-23 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("single_pages", "0006_alter_showtime_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="showtime",
            name="location",
        ),
    ]
