# Generated by Django 5.1.4 on 2024-12-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showtimes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="movie_chain",
        ),
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="movies/"),
        ),
    ]
