# Generated by Django 5.1.4 on 2024-12-23 23:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("showtimes", "0003_remove_showtime_duration_movie_duration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="showtime",
            options={"ordering": ["show_date", "show_time"]},
        ),
    ]
