# Generated by Django 5.1.4 on 2024-12-23 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("single_pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showtime",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="single_pages_showtimes_at_location",
                to="single_pages.movielocation",
            ),
        ),
    ]
