# Generated by Django 5.1.4 on 2024-12-23 02:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("showtimes", "0002_initial"),
        ("showtimes", "0002_movie_image"),
    ]

    operations = []
