# Generated by Django 5.1.4 on 2024-12-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showtimes", "0003_merge_0002_initial_0002_movie_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="showtime",
            old_name="showtime",
            new_name="show_time",
        ),
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
